### ISSUE TITLE
Chat unique link

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#1]
Write a controller: `/backend/api/index.js` - `POST` endpoint

- [ ] use a hash/uuid to create a unique link
- [ ] create db entry (dependent on #6 )
- [ ] format and return link.

Suggested response: 
```
{
   hash: <generated unique string>,
   formattedLink: <somedomain.com>/chat/<hash>
}
```

**Comment by Yogita98** [comment]
@muke1908 is this issue up for grabs?

**Comment by muke1908** [comment]
> @muke1908 is this issue up for grabs?

@Yogita98 Sure! To create db entry please use utils `insertInDb ` in `/backend/db/index.js`

**Comment by Yogita98** [comment]
@muke1908 so you just want to create a hash function?

**Comment by muke1908** [comment]
@Yogita98 
Take a look at this file https://github.com/muke1908/chat-e2ee/blob/master/backend/api/index.js

Currently, if you hit a `POST` request to `http://localhost:3001/api/getLink`([Line 10](https://github.com/muke1908/chat-e2ee/blob/0a5d1b31312fa92d822d20095a70326fd47e480f/backend/api/index.js#L10)),
it will return `{ status: 'OK' }` ([Line 21](https://github.com/muke1908/chat-e2ee/blob/0a5d1b31312fa92d822d20095a70326fd47e480f/backend/api/index.js#L21)) as a response.

The goal is to 
1. create a unique id You can use `uuid` as well to create a unique id. https://www.npmjs.com/package/uuid 
2. store it to db 
3. send it as the response. 

So, at line 20, you can add your implementation, and replace the response so that each time you hit `POST` to `/getLink`, it returns a unique link every time.
