### ISSUE TITLE
Write an endpoint(DELETE) that mark the chat link as deleted

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#101]
Write a controller at https://github.com/muke1908/chat-e2ee/blob/master/backend/api/chatLink/index.js
DELETE - `/chat-link/delete/<hash>` - this will select the resource by hash and patch as `deleted: true`.

Example resource structure is: 
```
{
   "hash": "a2ceea03-7f1e-4393-ba9c-a6ff477eb701",
   "link": "/chat/a2ceea03-7f1e-4393-ba9c-a6ff477eb701",
   "absoluteLink": "https://chat-e2ee.azurewebsites.net/chat/a2ceea03-7f1e-4393-ba9c-a6ff477eb701",
   "expired": false,
   "deleted": false
}
```
Refer: https://github.com/muke1908/chat-e2ee/issues/95

**Comment by nafees87n** [comment]
Should invalid links be updated or not?
`{
   expired:true,
   deleted:false
}`
In this case the link should be deleted or not?

**Comment by muke1908** [comment]
> Should invalid links be updated or not?
> `{ expired:true, deleted:false }`
> In this case the link should be deleted or not?

Yes, you are correct.

**Comment by muke1908** [comment]
@nafees87n can you also please document it in readme? https://github.com/muke1908/chat-e2ee#apis

**Comment by muke1908** [comment]
@nafees87n would you take a look at https://github.com/muke1908/chat-e2ee/issues/106 ?
