### ISSUE TITLE
FIX: rest api url structure 

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#106]
REST api endpoint should only point a resource. In url `verb`  should be avoided and should be used appropriate method instead.
ref: https://restfulapi.net/resource-naming/

example: 

**Bad**:
POST -> /chat-link/generate
GET -> /chat-link/validate/:channel
POST -> /chat/send
DELETE -> /chat-link/delete/:channel

**Good**:
CREATE-> /chat-link/
GET -> /chat-link/status/:channel
POST -> /chat/message
DELETE -> /chat-link/:channel

**Comment by nafees87n** [comment]
Okay
I'll do it
