### ISSUE TITLE
Add websocket to the project

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#109]
Add socket.io to both client and server.
In the scope of this issue, just create utilities that establish a connection between client and server.

**Comment by muke1908** [comment]
Related issue: https://github.com/muke1908/chat-e2ee/issues/113

**Comment by nafees87n** [comment]
@muke1908 I am not able to understand the socket.io implementation referring the official docs. Can you help me ?

**Comment by muke1908** [comment]
Hi @nafees87n, all the socket related code is written in https://github.com/muke1908/chat-e2ee/tree/master/backend/socket.io
