### ISSUE TITLE
Store messages in session storage

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#114]
Earlier we were using pubnub, therefore we used to store the messages (encrypted) on pubnub server for a short time. As we replaced the pubnub completely, and not storing messages (encryped) on any server, just for a better UX store it in sessionStorage so that on refresh, the browser can load it locally and decrypt (try) it.

https://github.com/muke1908/chat-e2ee/blob/e08a23673a24cd41967c9d2d4dadb4ed1b39f0bf/client/src/pages/messaging/index.js#L146

imo, the best place call function to put in in storage is while handling new message entry.
https://github.com/muke1908/chat-e2ee/blob/e08a23673a24cd41967c9d2d4dadb4ed1b39f0bf/client/src/components/Messaging/Message.js#L24

**Comment by gagan-aryan** [comment]
I would like to work on this @muke1908

**Comment by muke1908** [comment]
Hi @gagan-aryan, are you still working on it?

**Comment by gagan-aryan** [comment]
No @muke1908 I am not working on this. Sorry for keeping it assigned for too long. A bit busy with the coursework 😅

**Comment by muke1908** [comment]
@gagan-aryan No worry!

**Comment by pavan5555** [comment]
hey! anyone working on it ?

**Comment by muke1908** [comment]
@pavan5555 I don't think so. You can take it if you want.

**Comment by pavan5555** [comment]
@muke1908 Awesome! I will work on this then.

**Comment by Hassan-Ib** [comment]
Hey  @muke can I work this

**Comment by muke1908** [comment]
@Hassan-Ib cool, go ahead!

**Comment by Hassan-Ib** [comment]
hey @muke1908  , l just want to know if i get this right , so  on message received  - it should be stored in session storage right?

**Comment by muke1908** [comment]
Hi @Hassan-Ib, yes,  it's correct!

**Comment by Hassan-Ib** [comment]
i am having issue is the 3001 and also can you help me out with .env.sample configuration ... i don't know anything about that .. i don't know what it does

**Comment by Hassan-Ib** [comment]
MONGO DB ERROR!
i get when i run "npm run dev"

**Comment by muke1908** [comment]
@Hassan-Ib can you share more detail about the error that you are getting?

**Comment by muke1908** [comment]
@Hassan-Ib So have you create a mongo db instance. You can create one for free here https://www.mongodb.com

**Comment by Hassan-Ib** [comment]
> @Hassan-Ib So have you create a mongo db instance. You can create one for free here https://www.mongodb.com

i have never worked with mongoDb before

**Comment by muke1908** [comment]
@Hassan-Ib no worry, it's pretty simple. 
Once you create an account https://www.mongodb.com here, click on "Create cluster" button. Then you'll get all the required information there.
Let me know if you get stuck.

**Comment by J-16** [comment]
Hey @muke1908, Do we have anything for hacktoberfest?

**Comment by muke1908** [comment]
> Hey @muke1908, Do we have anything for hacktoberfest?

If you want to contribute to the project or have some features to implement feel free to share (You can write at [gitter](https://gitter.im/chat-e2ee/community) as well). I'll create a ticket and add the required tag for hacktoberfest.

**Comment by maxwebbnz** [comment]
Hi @muke1908, do you know if anyone is actively working on this? Would love to contribute.

**Comment by muke1908** [comment]
Hi @maxwebbnz, no one is working on it. You can take it! 
Let me know if you need any help in setting up the project.

**Comment by maxwebbnz** [comment]
@muke1908 Hi, all forked and ready to go however in loading the dev server, it is returning a blank page. No errors are coming up in my terminal, any advice? 

`jw@Maxs-MacBook-Pro chat-e2ee % npm run dev

> chat-e2ee@1.0.0 dev
> concurrently "npm run client" "npm run server"

[1] 
[1] > chat-e2ee@1.0.0 server
[1] > cross-env NODE_ENV=development nodemon index
[1] 
[0] 
[0] > chat-e2ee@1.0.0 client
[0] > cd client && npm start
[0] 
[1] [nodemon] 2.0.4
[1] [nodemon] to restart at any time, enter `rs`
[1] [nodemon] watching path(s): *.*
[1] [nodemon] watching extensions: js,mjs,json
[1] [nodemon] starting `node index index.js`
[0] 
[0] > client@0.1.0 start
[0] > react-scripts start
[0] 
[1] Websocket is up!
[1] Server running at 3001
[0] ℹ ｢wds｣: Project is running at http://192.168.0.75/
[0] ℹ ｢wds｣: webpack output is served from 
[0] ℹ ｢wds｣: Content not from webpack is served from /Users/mjw/chat-e2ee/client/public
[0] ℹ ｢wds｣: 404s will fallback to /
[0] Starting the development server...
[0] 
[0] Browserslist: caniuse-lite is outdated. Please run:
[0] npx browserslist@latest --update-db
[0] Compiled successfully!
[0] 
[0] You can now view client in the browser.
[0] 
[0]   Local:            http://localhost:3000
[0]   On Your Network:  http://192.168.0.75:3000
[0] 
[0] Note that the development build is not optimized.
[0] To create a production build, use npm run build.
[0] `

**Comment by muke1908** [comment]
Is it returning a blank page at localhost:3000 ?

**Comment by maxwebbnz** [comment]
> Is it returning a blank page at localhost:3000 ?

Yep blank page.

**Comment by muke1908** [comment]
Any error in the developer console of the browser?

**Comment by maxwebbnz** [comment]
> Any error in the developer console of the browser?

Nope, nothing out of the ordinary anyway. Just some 500 errors for fonts....

This .env file looks fine  aye (retracted sensitive information)?

```
MONGO_URI='mongodb+srv://@cluster0.hr8j2.mongodb.net'
MONGO_DB_NAME='chat2ee'
CHAT_LINK_DOMAIN=''
IMAGE_BB_API_KEY=''
IMGUR_API_KEY''
```

**Comment by muke1908** [comment]
mongo uri looks incorrect. 
Can you try removing both mongo uri and mongo db name?

**Comment by maxwebbnz** [comment]
Nope, still nothing.

**Comment by muke1908** [comment]
This is surprising. 
 - Can you see any activity in the network tab? 
 - What you see, if you do inspect element? 
 
Does this link work for you? https://chat-e2ee.herokuapp.com/

**Comment by latishpavan** [comment]
Hi @muke1908 I recently came across this project and found it interesting. I would like to contribute to this issue if no one is actively working on it!

**Comment by muke1908** [comment]
@latishpavan sure, go ahead

**Comment by iHDeveloper** [comment]
Hello, It seems this issue is being re-assigned over and over. May I take over it and try to finish it in a day or two inshallah?

Interestingly though, this issue when it gets resolved, it opens up the possibility of "disappearing messages" and other featuers that interacts with the storage. :)

**Comment by muke1908** [comment]
> Hello, It seems this issue is being re-assigned over and over. May I take over it and try to finish it in a day or two inshallah?
> 
> Interestingly though, this issue when it gets resolved, it opens up the possibility of "disappearing messages" and other featuers that interacts with the storage. :)

sure go ahead. Thanks!

**Comment by iHDeveloper** [comment]
@muke1908 sorry for annoying, would the user be able to switch between local and session storages? I'm wondering.

**Comment by muke1908** [comment]
@iHDeveloper Hi, I think we can't store it in localStorage because the private key is stored in sessionStorage.

**Comment by iHDeveloper** [comment]
@muke1908 Hello, Sorry for being late, I was over-stressed. I have done the implementation. I'm just struggling with debugging the service. I'm encountering issues such as the user joining but it's not marked online and others.

Would you like me to push it as a PR? So, you can test it yourself and from there I can do the changes faster. I would like to hear your advice. :)

Thank you. May God bless you.
iHDeveloper

**Comment by muke1908** [comment]
@iHDeveloper Hi, yes there was an issue. It's probably fixed now. You can open your PR, I'll take a look.

Thanks!
