### ISSUE TITLE
handle disconnected/redundant clients 

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#115]
In case the socket is not available in the current socket instance, send a disconnect event and remove it from the client list (The list that is maintained in memory.)

https://github.com/muke1908/chat-e2ee/blob/e08a23673a24cd41967c9d2d4dadb4ed1b39f0bf/backend/socket.io/index.js#L21

```if(!socket)```
->  delete the client form `clientRecord`
https://github.com/muke1908/chat-e2ee/blob/e08a23673a24cd41967c9d2d4dadb4ed1b39f0bf/backend/socket.io/clients.js#L1
-> Get receiver from the `clientRecord`, if avaiable, emit disconnect event `receiverSocket.emit('on-alice-disconnect');`

Ref: https://github.com/muke1908/chat-e2ee/blob/e08a23673a24cd41967c9d2d4dadb4ed1b39f0bf/backend/socket.io/listeners.js#L26

**Comment by nafees87n** [comment]
>-> Get receiver from the clientRecord, if avaiable, emit disconnect event receiverSocket.emit('on-alice-disconnect');

Not able to understand this part

**Comment by muke1908** [comment]
I just realized this issue is invalid. It's actually handled in https://github.com/muke1908/chat-e2ee/blob/3cae4cefcc94604b6c018216ec40c7e85d98c25f/backend/socket.io/listeners.js#L38

**Comment by muke1908** [comment]
@nafees87n check if this is something you want to take a look on https://github.com/muke1908/chat-e2ee/issues/127

**Comment by nafees87n** [comment]
@muke1908 I am already working on that issue. Would you please assign it to me

**Comment by muke1908** [comment]
@nafees87n write any comment on that issue (#127), then I would be able to assign you.
