### ISSUE TITLE
Add imgur api integration

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#117]
https://apidocs.imgur.com/#c85c9dfc-7487-4de2-9ecd-66f727cf3139

Currently, there is the only [integration](https://github.com/muke1908/chat-e2ee/blob/master/backend/external/imagebb.js) that is https://imgbb.com/
Add support for imgur as well, let the developer choose the hosting.

**Comment by Opyskoty** [comment]
Hi, can I please take a stab at this?

**Comment by muke1908** [comment]
@Opyskoty Hey sure!!

**Comment by vvkpd** [comment]
I would like to work on this card please let me know if no one is working on it.
Thanks

**Comment by muke1908** [comment]
@vvkpd Hi, sure!
@Opyskoty most likely not working on it.

**Comment by code-star-1** [comment]
Can I take this issue?

**Comment by muke1908** [comment]
@code-star-1 sure!

**Comment by carmonaalex12** [comment]
I'd like to take a crack at it!

**Comment by muke1908** [comment]
@carmonaalex12 sure!

**Comment by badcaptcha** [comment]
Hasn't been an update in awhile, can I give it  try?

**Comment by muke1908** [comment]
@badcaptcha hi! Sure, go ahead

**Comment by GJ-16** [comment]
Hey, can you please tell me what has to _be done briefly_ ? May be I can work on this.

**Comment by muke1908** [comment]
Hi, may be you can look into existing integration https://github.com/muke1908/chat-e2ee/blob/master/backend/external/imagebb.js

Similarly, you can implement Imgur API integration https://apidocs.imgur.com/#c85c9dfc-7487-4de2-9ecd-66f727cf3139

**Comment by GJ-16** [comment]
Hey sure, I'm on it.

**Comment by GJ-16** [comment]
@muke1908 Mate, I have some doubts.
__1.__ I replaced the existing imgbb with imgur. But you state
> Add support for imgur as well, let the developer choose the hosting. 

How to do that?


__2.__ I have integrated just the anonymous part as per this link you provided 
> Similarly, you can implement Imgur API integration https://apidocs.imgur.com/#c85c9dfc-7487-4de2-9ecd-66f727cf3139

Is this fine or do I need to do Authorization as well?

**Comment by muke1908** [comment]
@GJ-16 authorization is not required.
