### ISSUE TITLE
Allow user to remove image attachment.

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#118]
Currently, there is no way to remove image attachment once it's selected. Add a cross button, clicking on that it should remove the image attachment. 

Ref design:
![Untitled](https://user-images.githubusercontent.com/20297989/91602150-816aea80-e973-11ea-9f0f-07bbdb08b125.png)

**Comment by Ryuuko** [comment]
Hi! I would like to take part of it. But I have a probably stupid question....I can't load reCAPTCHA in my local host and therefore can't load the messaging page. So how can I run the messaging page in my local host, so that I can manipulate the button there?

**Comment by Ryuuko** [comment]
Ok I've found the way out, simply just make a ID number like http://localhost:3000/chat/123/ hahahahaha
Can I work with this issue?
