### ISSUE TITLE
Allow user to delete chat link.

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#119]
API:   `DELETE` -> `/chat-link/:channel`

https://github.com/muke1908/chat-e2ee/blob/e08a23673a24cd41967c9d2d4dadb4ed1b39f0bf/backend/api/chatLink/index.js#L47

Add a floating button to the [messaging page ](https://github.com/muke1908/chat-e2ee/blob/master/client/src/pages/messaging/index.js)

Once clicked, it should ask for confirmation, and on confirming it should make the call for deleting the link.

**Comment by StijnLammers** [comment]
I would like to take on this issue.

I am quite new to github and programming in general, and I'm not sure if this is the right place to ask this question. But when setting up the developer server I don't know what to put after CHAT_LINK_DOMAIN. I figured all the other stuff out but I'm stuck on this.

**Comment by StijnLammers** [comment]
Thanks for you quick answer!

I was getting an error when generating the link and thought that this would fix it, but it didn't.
![Error Image](https://user-images.githubusercontent.com/52537077/92260329-060bba80-eed8-11ea-8327-8d9a62d3c823.png)
Any idea what this could be?

**Comment by muke1908** [comment]
@StijnLammers Did you configure the database (Mongodb) ?

**Comment by StijnLammers** [comment]
I have, but I may have made some mistakes there.
I assumed I just needed a random db so I made one on mongodb with azure. I clicked "connect" and copied the link into the .env file, which looks like this: "mongodb+srv://<myaccname>:<myaccpassword>@cluster0.i12dp.azure.mongodb.net".

I made a collection and a db within that collection named chat, which is what I used to put behind MONGO_DB_NAME.

**Comment by muke1908** [comment]
if db name is chat, MONGO_DB_NAME=chat

**Comment by StijnLammers** [comment]
Alright I finally got it to work. It was some kind of network issue.

**Comment by nik2490** [comment]
Is this issue open to work on @muke1908 ?

**Comment by muke1908** [comment]
Hi @nik2490, yes it's open. @StijnLammers can you please confirm?

**Comment by StijnLammers** [comment]
@muke1908 @nik2490 I can confirm

**Comment by manny525** [comment]
Is this issue still open @muke1908 @StijnLammers?

**Comment by muke1908** [comment]
Hi @manny525! yes, it's still open.

**Comment by manny525** [comment]
![chate2ee](https://user-images.githubusercontent.com/60325174/94788532-526fea80-03f1-11eb-83f1-0d82fe2f2ad7.JPG)

Not able to open the chat window after link generation.

**Comment by manny525** [comment]
Why is the link not being deleted from the database? Isn't it useless to keep the link after the deleted boolean has been marked true?

**Comment by muke1908** [comment]
@manny525 in general, deleting data is always **not recommended** - leads to inconsistency, potential data loss, difficulty in debugging and many more reason. So **soft delete** is always a better bet. 

Although in the scope of this project, we can actually delete the links form database. But I would still suggest to keep it as we can at-least count how many links have been generated so far - gives an rough idea how many users are using it.

**Comment by manny525** [comment]
> @manny525 in general, deleting data is **not recommended** in most of the cases - leads to inconsistency, accidental data loss, difficulty in debugging and many more reasons. So **soft delete** is always a better bet.
> 
> Although in the scope of this project, we can actually delete the links form database. But I would still suggest to keep it as we can at-least count how many links have been generated so far - gives a rough idea how many users are using it.
> 
> May be in future, we'll start hard deleting and keep the total count somewhere else.

Alright,
