### ISSUE TITLE
Add a button that would bring up the emoji row

### ISSUE THREAD

**Issue by gagan-aryan** [muke1908/chat-e2ee#122]
Currently, emoji row always stays on top of the message input bar. Add an emoji icon (button) next to the image picker that would bring up the emoji row instead of always having it on the top.

Messaging page route: `/chat/<link>`

Ref component file: 
https://github.com/muke1908/chat-e2ee/blob/544f2c6fde6c2d50f3c4ad6c7e1ea3862a80d6ab/client/src/components/Messaging/NewMessageForm.js#L30

**Comment by Heisenberg399** [comment]
Can I work on this?

**Comment by muke1908** [comment]
@Heisenberg399  sure!

**Comment by salonigoyal2309** [comment]
hey , i am just starting with open source contributions and would love to work on this issue , is this issue still open ?

**Comment by muke1908** [comment]
@salonigoyal2309 sure! 
Most likely @Heisenberg399 is not working on it.

**Comment by muke1908** [comment]
hi @Heisenberg399 ! can you confirm the above?

**Comment by Heisenberg399** [comment]
Yes @salonigoyal2309  you can go ahead...I am busy with my exams.

**Comment by muke1908** [comment]
@all-contribtors please add @salonigoyal2309 for code

**Comment by muke1908** [comment]
@all-contributors please add @salonigoyal2309 for code
