### ISSUE TITLE
Informing the user if someone joins the chat by giving a message in the chat section

### ISSUE THREAD

**Issue by loneWarrior581** [muke1908/chat-e2ee#124]
**When someone joins the chat the other person is not aware about his presence by giving a small message in the chat section**

 **Solution** 
By initiating a small message saying _**someone just joined**_ in the chat section by the so called bot for the users already present in that room so that they can start conversation. 

**Alternatives**
We can create a section in the room section so describing the persons active in the room so that its easy for others to start the conversation

**Comment by muke1908** [comment]
Hi @loneWarrior581, we show it on the top left corner. However, for better messaging, there is already an issue #33 

![Screen Shot 2020-08-29 at 5 46 55 PM](https://user-images.githubusercontent.com/20297989/91639548-0e6b7d80-ea20-11ea-9c12-8127f936c265.jpg)

**Comment by loneWarrior581** [comment]
This type of UI would look better i think 
![roomname](https://user-images.githubusercontent.com/67538935/91640548-fdc90080-ea3b-11ea-9c88-48edaa00c891.PNG)

**Comment by muke1908** [comment]
Closing - duplicate #33
