### ISSUE TITLE
Allow user to select only the images and not the other files to be sent 

### ISSUE THREAD

**Issue by loneWarrior581** [muke1908/chat-e2ee#125]
The current version only allows the images(.jpg) files to be sent and not the pdf and docs but yet the user is able to select form the chat section.
**Solution**
Allow user to select only the the .jpg files and not other files

**Comment by gagan-aryan** [comment]
@muke1908 is the secure image sharing already implemented?

**Comment by muke1908** [comment]
@gagan-aryan No, nothing is done yet.

**Comment by muke1908** [comment]
> @gagan-aryan No, nothing is done yet.
I have created an issue: 
https://github.com/muke1908/chat-e2ee/issues/129

**Comment by loneWarrior581** [comment]
@muke1908 Sir can you tell me where I can find the required file for the same

**Comment by muke1908** [comment]
@loneWarrior581 Hi I think it's pretty simple, just take a look at https://github.com/muke1908/chat-e2ee/blob/2cdbc97e69724f95d99d1b4624f13680847c947c/client/src/components/Messaging/ImagePicker/index.js#L21

**Comment by loneWarrior581** [comment]
@muke1908  sir I am getting issues while commiting the necessesary changes so can you help me the right way to make my commit.<br> 
![cmd](https://user-images.githubusercontent.com/67538935/92309423-1056b300-efc3-11ea-9cc6-f14d2d0ee108.PNG)

**Comment by muke1908** [comment]
@loneWarrior581 Hi, this is not error. 
How are you trying to commit though?

**Comment by loneWarrior581** [comment]
@muke1908  sir I am using the usual way i.e. **_git commit -m"commit message"_** for making my commit but it gets stuck at this point. So can you tell me way to get out of this.

**Comment by muke1908** [comment]
@loneWarrior581 I am not sure why it's getting stuck for you. You might want to skip the hook by adding ` --no-verify`
`git commit -m"commit message"  --no-verify`

**Comment by muke1908** [comment]
@all-contributors please add @loneWarrior581 for code.
