### ISSUE TITLE
Implement 'Delivery receipt'

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#127]
Show a "delivered" receipt for messages when it's delivered to the client. 

If a message with id `x-y-z` is sent from client1, client1 should mark the message as delivered once the socket in client2 [receives](https://github.com/muke1908/chat-e2ee/blob/a5c87b9fd6d52ce727a7ce74734711235572ef69/client/src/pages/messaging/index.js#L206), send an event `message-delivered` to the client1 and display 'delivered' at client1

For id, use timestamp for each message. 

Ref:
<img width="867" alt="Screen Shot 2020-09-02 at 9 38 09 AM" src="https://user-images.githubusercontent.com/20297989/91940394-0cdfd500-ed00-11ea-84ce-135034d5de87.png">

**Comment by nafees87n** [comment]
I would like to work on it
