### ISSUE TITLE
Zooming the attached image when clicked 

### ISSUE THREAD

**Issue by loneWarrior581** [muke1908/chat-e2ee#136]
**Problem**
When a image is being sent the content are not visible as the images are not been able to zoom <br>
**Solution**
We can add the the zooming functionality when clicked by the user:

If user clicks on the attached image, show it in larger size may be in a popup.

![91602150-816aea80-e973-11ea-9f0f-07bbdb08b125](https://user-images.githubusercontent.com/20297989/95174873-5457f600-07c3-11eb-97d2-5f74ac80f12c.png)

**Comment by muke1908** [comment]
@loneWarrior581 can you also add a screenshot for reference.

**Comment by loneWarrior581** [comment]
@muke1908 sir is the issue open

**Comment by muke1908** [comment]
Hi @loneWarrior581, yes it's still open.

**Comment by gabrielatricak** [comment]
Hi I would like to work on this for a school project. Can I be assigned to this?

**Comment by muke1908** [comment]
@gabrielatricak hi, yes sure!

**Comment by gabrielatricak** [comment]
I have some issues with database: when i try to run with npm run dev I get Mongo DB Error and when I opened localhost:3001 i got blank page only with: cant serve production build in dev mode, please open react dev server

Získajte Outlook pre iOS<https://aka.ms/o0ukef>
________________________________
Od: Mukesh <notifications@github.com>
Odoslané: Sunday, October 4, 2020 6:58:25 PM
Komu: muke1908/chat-e2ee <chat-e2ee@noreply.github.com>
Kópia: Gabriela Tričáková <gabriela.tricakova@student.tuke.sk>; Assign <assign@noreply.github.com>
Predmet: Re: [muke1908/chat-e2ee] Zooming the attached image when clicked (#136)


Assigned #136<https://github.com/muke1908/chat-e2ee/issues/136> to @gabrielatricak<https://github.com/gabrielatricak>.

**Comment by muke1908** [comment]
You have to setup mongodb. You can get one instance for free from
https://www.mongodb.com/
If you find any difficulties in setting up mongo let me know.

**Comment by gabrielatricak** [comment]
Yep i have done that, i created a cluster, user, added ip adresses, and then connected cluster through mongo shell ... but still the same .. i've also created a .env inside my chat-e2ee folder and added all information
________________________________
Od: Mukesh <notifications@github.com>
Odoslané: nedeľa 4. októbra 2020 21:53
Komu: muke1908/chat-e2ee <chat-e2ee@noreply.github.com>
Kópia: Gabriela Tričáková <gabriela.tricakova@student.tuke.sk>; Mention <mention@noreply.github.com>
Predmet: Re: [muke1908/chat-e2ee] Zooming the attached image when clicked (#136)


You have to setup mongodb. You can get one instance for free from
https://www.mongodb.com/
If you find any difficulties in setting up mongo let me know.

**Comment by muke1908** [comment]
You don't need to connect it from mongo shell.
Just add those in your .env It will look like ->
MONGO_URI=mongodb+srv://<username>:<password>@cluster0-zbsik.mongodb.net

Also, make sure, your IP address is whitelisted in mongodb.com admin
dashboard. In case you can't set it up drop me a mail at mukeshbsws[at].
gmail.com I'll share the required keys.

**Comment by manny525** [comment]
@muke1908 do you mind assigning this to me?

**Comment by muke1908** [comment]
Hi @manny525 , @gabrielatricak is already working on it. 
You can take a look at #114

**Comment by manny525** [comment]
Sure. I'll have a look at it.

**Comment by muke1908** [comment]
Hi @gabrielatricak, just wanted to confirm if you are working on it.

**Comment by gabrielatricak** [comment]
Hi, yes I am still working on it. I think today or tommorow I will be done.

Získajte Outlook pre iOS<https://aka.ms/o0ukef>
________________________________
Od: Mukesh <notifications@github.com>
Odoslané: Monday, October 19, 2020 1:16:38 PM
Komu: muke1908/chat-e2ee <chat-e2ee@noreply.github.com>
Kópia: Gabriela Tričáková <gabriela.tricakova@student.tuke.sk>; Mention <mention@noreply.github.com>
Predmet: Re: [muke1908/chat-e2ee] Zooming the attached image when clicked (#136)


Hi @gabrielatricak<https://github.com/gabrielatricak>, just wanted to confirm if you are working on it.

**Comment by naveen8801** [comment]
hi @muke1908 , i am new to open source and wanna contribute , i found this issue suitable for me , would you assign it to me ?

**Comment by muke1908** [comment]
@naveen8801 Sure. 
@gabrielatricak worked on it earlier and (s)he already implemented the basic zoom feature. You can check and improve UI/UX if you have anything in mind.

**Comment by naveen8801** [comment]
@muke1908 sure , thanks .

**Comment by GJ-16** [comment]
@muke1908 Do you have any suggestion?

**Comment by amulagrawal02** [comment]
Is this issue is resolve or not?

**Comment by amulagrawal02** [comment]
Yes  I'm interested to fix this bug

**Comment by muke1908** [comment]
@amulagrawal02 , sure!
