### ISSUE TITLE
Add timestamp to message

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#149]
While sending message add timestamp to the [message objec](https://github.com/muke1908/chat-e2ee/blob/169a1d984fd8e92744ae1de46eca4a2e6ca65fb4/backend/api/messaging/index.js#L33)t and display it on UI.

**Comment by abhishek-aa** [comment]
Hi. I can get this done. I have worked with live chat using WebSockets. Please assign me this issue!

**Comment by muke1908** [comment]
@all-contributors please add @abhishek-aa for code.
