### ISSUE TITLE
API: take PIN in request param and return link object

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#159]
write a controller (`GET` endpoint) that takes PIN and return valid link obj from db.

Let's assume PINs are valid for 30min. Hence, it will **NOT** return the link obj if currentTime - pinCreationTime > 30*60*1000 i.e. status `404`.

---

You'll have to write an API for example: GET- > /chat-link/<pin>
```
router.get(
  '/:pin',
  asyncHandler(async (req, res) => {
    const { pin } = req.params;
    ... your code to find link from db.
);
```
use util function `findOneFromDB` to find link by pin.

Ref file: https://github.com/muke1908/chat-e2ee/blob/master/backend/api/chatLink/index.js

**Comment by yatharthMogra** [comment]
hey @muke1908, I am intrested in taking up this issue can you expand a little more

**Comment by muke1908** [comment]
Hi @yatharthMogra sure!
You'll have to write an API for example:  `GET`- > `/chat-link/<pin>`
```
router.get(
  '/:pin',
  asyncHandler(async (req, res) => {
    const { pin } = req.params;
    ... your code to find link from db.
);
```
use util function [findOneFromDB](https://github.com/muke1908/chat-e2ee/blob/f28a1eae86363f7f8754bc7298e93e0c480734ff/backend/db/index.js#L24) to find link by pin.

Most of the controllers are written here: https://github.com/muke1908/chat-e2ee/blob/master/backend/api/chatLink/index.js
You can take a look for example.

Let me know if you have any issue in setting up the project.
