### ISSUE TITLE
UI: Join chat by entering PIN

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#160]
Create this section below the link generation section in the [index page](https://github.com/muke1908/chat-e2ee/blob/master/client/src/pages/chatlink/index.js)

- [ ] Provide an input box to enter PIN. 
- [ ] Should be **Join button** next to the input box.
- [ ] On pressing join button it should call [API](https://github.com/muke1908/chat-e2ee/issues/159).
- [ ] If PIN is valid, redirect to the link else, show error.

**Comment by aayushmau5** [comment]
Hey @muke1908, may i work on this one ?

**Comment by muke1908** [comment]
@aayushmau5 Sure!

**Comment by aayushmau5** [comment]
hey @muke1908, is there any component for input field, or should i make one myself? Also this Input and join button should be on the captcha page and Not in generated link page, right ?

**Comment by muke1908** [comment]
> is there any component for input field, or should i make one myself? 

No, we don't have a re-usable component.

>Also this Input and join button should be on the captcha page and Not in generated link page, right ?
captcha page and Not in generated link page

Yes, it should be there before link is generated as you said captcha page. (However, captcha is removed)

**Comment by aayushmau5** [comment]
Hey @muke1908, so we removed the captcha and now we are adding a PIN system. I have made an input component but the value of the text field is in its own component, any idea how i can "export" the value of the text field to the `index.js` file. I'm sorry but i'm kinda learning react, so forgive me if it sounds like a stupid question.

**Comment by aayushmau5** [comment]
![image](https://user-images.githubusercontent.com/54525741/94944889-859ca180-04f7-11eb-8a00-b54f445f52f2.png)

Also, Progress so far. Lemme know if you need any change. Though it is a WIP.

**Comment by muke1908** [comment]
Hi @aayushmau5, I am sorry I haven't attached any design earlier. Here is the suggested design, let's keep it simple and clean.
![Untitled](https://user-images.githubusercontent.com/20297989/94950399-40727280-04eb-11eb-9ab2-c36b3750ba9f.png)

**Comment by muke1908** [comment]
> Hey @muke1908, so we removed the captcha and now we are adding a PIN system. I have made an input component but the value of the text field is in its own component, any idea how i can "export" the value of the text field to the `index.js` file. I'm sorry but i'm kinda learning react, so forgive me if it sounds like a stupid question.

Hi, no problem! You can push your code to a branch and create a draft PR. Then I would be able to help you there.

**Comment by aayushmau5** [comment]
> Hi, no problem! You can push your code to a branch and create a draft PR. Then I would be able to help you there.

I'm using props to pass down the PIN. So it's all good. Also thanks for the design image.

**Comment by aayushmau5** [comment]
![image](https://user-images.githubusercontent.com/54525741/94954990-80dfe980-0507-11eb-9ee8-9d6db049ab83.png)

@muke1908 How's this ?

**Comment by aayushmau5** [comment]
So i made the input as well as button as a whole component. Now, is the API ready? We can then hook it up with the button.

**Comment by muke1908** [comment]
@aayushmau5 the api is not ready. But you can write the [service in client ](https://github.com/muke1908/chat-e2ee/tree/master/client/src/service) assuming the endpoint is GET - `/chat-link/<pin>`. for more look [ref issue](https://github.com/muke1908/chat-e2ee/issues/159)

**Comment by aayushmau5** [comment]
Help me understand the routes. So i made this service. So what's happening here ? What's the route looks like to the server ?
```js
import makeRequest from '../utils/makeRequest';

const getLink = async (pin) => {
  return makeRequest(`/chat-link/${pin}`, {
    method: 'GET'
  });
};

export default getLink;

```

Is `/chat-link/` equivalent to `/` ?

**Comment by muke1908** [comment]
@aayushmau5 
In your code, you are making an api call to server - GET request. The endpoint looks like `/api/chat-link/<pin>` Check the function [makeRequest](https://github.com/muke1908/chat-e2ee/blob/d62c01ce3c4c85c682c3bb7f7b5b2a0806b6dc45/client/src/utils/makeRequest.js#L2)

In server, we are handling all requests at `/api/*` check [app.js](https://github.com/muke1908/chat-e2ee/blob/d62c01ce3c4c85c682c3bb7f7b5b2a0806b6dc45/app.js#L13)

Chat link specific controllers are in [backend/api/index.js](https://github.com/muke1908/chat-e2ee/blob/d62c01ce3c4c85c682c3bb7f7b5b2a0806b6dc45/backend/api/index.js#L13)

**Comment by aayushmau5** [comment]
Yup, i figured so. Here's the `GET` request handler i made.
```js
router.get(
  '/:pin',
  asyncHandler(async (req, res) => {
    const { pin } = req.params;
    await findOneFromDB({ pin: pin }, LINK_COLLECTION);
    return res.send(pin);
  })
);
```
I don't know what's `LINK_COLLECTION` doing but it's working. Tested by responding `pin`. Now, what should i do next ?

**Comment by muke1908** [comment]
`LINK_COLLECTION` is the collection name, defined at[ const.js](https://github.com/muke1908/chat-e2ee/blob/d62c01ce3c4c85c682c3bb7f7b5b2a0806b6dc45/backend/db/const.js)

Wondering how did you configure your mongo db?

**Comment by aayushmau5** [comment]
I'm using my own mongoDB instance. I had been working on some personal projects which required mongoDB so i made a mongoDB atlas database and used that.

**Comment by aayushmau5** [comment]
Now, what should i do next? I feel the API is kinda ready, we need to get the chat link based on the `PIN` and redirect the user to that link. I'm wondering how to get the chat link?

**Comment by muke1908** [comment]
` ``
const resp = await findOneFromDB({ pin: pin }, LINK_COLLECTION);`
return res.send(resp);
```

resp will have the link.

**Comment by aayushmau5** [comment]
Ok. so i was able to get the link. Now, how do i redirect to the link in react ? Sorry, still learning.

**Comment by muke1908** [comment]
You can use hook to get history. 
`import { useHistory } from "react-router-dom";`

Inside component, 

```
const history = useHistory();
history.push(`<link>`)
```

**Comment by muke1908** [comment]
@aayushmau5 https://github.com/muke1908/chat-e2ee/issues/159 is closed now, you might get some conflicts as you also wrote the same controller.

**Comment by aayushmau5** [comment]
Pretty cool. Hey, i'm getting a commit error. Something to do with `Husky`
```
husky > commit-msg (node v14.10.0)
⧗   input: "Add Join Chat By PIN Functionality : feat"
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
```

What to do ?

**Comment by muke1908** [comment]
@aayushmau5 valid commit message would be something like:
`feat: "Add Join Chat By PIN Functionality"`

**Comment by aayushmau5** [comment]
I'm pretty sure it is working. Should i make a PR to the `master` branch ?

**Comment by muke1908** [comment]
@aayushmau5 sure!

**Comment by aayushmau5** [comment]
@muke1908 Please check. https://github.com/muke1908/chat-e2ee/pull/167

**Comment by muke1908** [comment]
@aayushmau5 left a few comments.
