### ISSUE TITLE
UI: Show PIN along with the link.

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#161]
After generating chat link, show the generated PIN as well in the [index page](https://github.com/muke1908/chat-e2ee/blob/master/client/src/pages/chatlink/index.js). 
Also mention that the PIN is valid for 30min.
![Untitled](https://user-images.githubusercontent.com/20297989/94960749-0d84aa80-04fc-11eb-9ae4-c28a1322fb1c.png)

**Comment by abhaybhatt** [comment]
@muke1908 i want to work on this issue?

**Comment by muke1908** [comment]
@abhaybhatt sure!

**Comment by muke1908** [comment]
@abhaybhatt in case you are working on it, you can take reference form the attached design.

**Comment by manny525** [comment]
Is this issue still open or a pull request has been generated?

**Comment by muke1908** [comment]
@manny525 Not sure whether @abhaybhatt is working on it or not.
Hi @abhaybhatt can you please confirm?

**Comment by pavan5555** [comment]
Hi, I would like to work on this issue, is this still open ?

**Comment by muke1908** [comment]
Hi @pavan5555 please check with @manny525 once.

**Comment by pavan5555** [comment]
Hey @manny525 are working on this ?

**Comment by pavan5555** [comment]
Hi @muke1908  I just submitted a PR for this issue, I am new to the code contribution thing, I can't link the issue and the PR.

**Comment by manny525** [comment]
> Hey @manny525 are working on this ?

No, i'm not
