### ISSUE TITLE
UI: Fix alignment of buttons and text

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#171]
The delete button and theme toggle should be vertically aligned.
<img width="817" alt="Screen Shot 2020-10-08 at 10 22 45 AM" src="https://user-images.githubusercontent.com/20297989/95427499-5602f480-0950-11eb-98cd-37b889493119.png">

<img width="356" alt="Screen Shot 2020-10-08 at 10 25 07 AM" src="https://user-images.githubusercontent.com/20297989/95427740-b3974100-0950-11eb-8a01-3455f24a1713.png">

Earlier it was:
<img width="349" alt="Screen Shot 2020-10-08 at 10 25 45 AM" src="https://user-images.githubusercontent.com/20297989/95427770-bdb93f80-0950-11eb-9ea2-b6e15d9e8245.png">

Let's replace the **delete** button with an icon if it doesn't fit.

**Comment by aspanaich** [comment]
Hi @muke1908 , I would like to work on this issue.

**Comment by muke1908** [comment]
@aspanaich sure!

**Comment by aspanaich** [comment]
@muke1908 , Does this look alright?

Desktop view -
![desktop-view](https://user-images.githubusercontent.com/37369247/95449628-ab57f980-0982-11eb-8c0b-af30ad56ab46.png)

Mobile view -
![mobile-view](https://user-images.githubusercontent.com/37369247/95449633-ac892680-0982-11eb-9b3f-231455dac5c1.png)

**Comment by muke1908** [comment]
Yes, looks great!
