### ISSUE TITLE
Correct text instruction

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#177]
After generating link, it show's **Anyone with the PIN also can join the chat**

Change it to: Anyone with the **PIN** or the **Link** can join your chat

**Comment by Kishore-abhimanyu** [comment]
can you assign this to me?

**Comment by Kishore-abhimanyu** [comment]
can you please add hacktoberfest accepted tag?

**Comment by Kishore-abhimanyu** [comment]
can you please add *hacktoberfest-accepted* tag?
