### ISSUE TITLE
Mobile Support?

### ISSUE THREAD

**Issue by mamamia5x** [muke1908/chat-e2ee#186]
I don't know if it works on mobile, but whenever I try to get someone to join from their phone and it doesn't work.
It'll be nice to have the ability, but it may just be a safari thing.

**Comment by muke1908** [comment]
@mamamia5x thanks for reporting. It ideally should work on mobile, I will check though.

**Comment by mamamia5x** [comment]
Alrightm thanks.

**Comment by J-16** [comment]
Hey @mamamia5x, 

Can you say what you mean by not working? Is that the UI not fitting into the mobile? I mean the input field, emoji icon and send button?

**Comment by muke1908** [comment]
@J-16 I checked, and the messaging page is kind of broken - the send button is not visible in some smaller devices.

**Comment by J-16** [comment]
Hey @muke1908, 

I completed that, will do a pull request now. But I couldn't handle the send button when the image is selected.

**Comment by muke1908** [comment]
> Hey @muke1908,
> 
> I completed that, will do a pull request now. But I couldn't handle the send button when the image is selected.
> Can you help me with that?

Sure. You can open the PR. I'll work on that.

**Comment by J-16** [comment]
@muke1908, Done.

**Comment by mamamia5x** [comment]
Sorry for not responding, but it looks to be working fine now. Thanks.
