### ISSUE TITLE
Link generation UI

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#2]
The home route where users can generate a unique chat link.

- Basic instruction about the link and how it works.
- "Generate link" button. ref #20 
- Loader while generating the link.
- Show link.
- The link should pre-selected for copying.

Location: `./client/src/pages/chatlink`
Please refer to the UI below:  

![Link generation](https://user-images.githubusercontent.com/20297989/85107773-3025d880-b217-11ea-82e9-316532cf304a.png)

Related issue #1

**Comment by gagan-aryan** [comment]
I want to take up this issue. Can you guide me a bit?

**Comment by muke1908** [comment]
> I want to take up this issue. Can you guide me a bit?

You can start with this https://github.com/muke1908/chat-e2ee/issues/26

**Comment by gagan-aryan** [comment]
So just to clarify the generated link will no longer be a hyperlink, right?
