### ISSUE TITLE
Create a reusable button component

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#20]
Please take design reference from #2 
Create a react component for a button that should take the following as props.
 - label
 - type <primary|secondary> default: primary
 - state <active|disabled> default: active
 - onClick
 - width

**Comment by gagan-aryan** [comment]
I want to take up this issue. But I am having trouble setting up the project. When I run the 3001 port it says "Cant serve production build in dev mode, please open react dev server".

**Comment by muke1908** [comment]
@gagan-aryan 
When running, `npm run dev` you have to open localhost:3000 - react dev server should be running on this port.

**Comment by gagan-aryan** [comment]
Hey! I am drowned in a plethora of errors. Can you please help me with this?
![Screenshot from 2020-07-19 15-05-27](https://user-images.githubusercontent.com/62807661/87871847-9bf39080-c9d1-11ea-9738-5bbea214273c.png)

**Comment by muke1908** [comment]
@gagan-aryan , looks like you already have webpack installed which is incompatible. 
Did you try what steps it asking to follow? It should fix the issue.

1. delete package-lock.json both both `./package-lock.json` and `./client/package-lock.json`
2. delete node_modules - both ./node_modules and ./client/node_modules
3. Run npm install

**Comment by gagan-aryan** [comment]
Yes, I tried doing that. I still get the same error.

**Comment by muke1908** [comment]
@gagan-aryan that's pretty sad! You might want to delete and then setup the project.
Make sure you are using the latest node.

**Comment by gagan-aryan** [comment]
I setup the project again and reinstalled npm as well and then got the same error and followed the steps again. None of that helped, I have texted you on discord btw.

**Comment by gagan-aryan** [comment]
I have opened a PR please review it.

**Comment by muke1908** [comment]
Closing the issue as done, thanks for your contribution!
