### ISSUE TITLE
Status remains "Online" after chat deleted

### ISSUE THREAD

**Issue by softvisioneer** [muke1908/chat-e2ee#202]
**Is your feature request related to a problem? Please describe.**
When one of the chat participants deletes the chat the other participant gets a sound notification but the status remains "Online". The user either has to refresh the page or try and send a message in order to be notified about the chat deletion.

**Describe the solution you'd like**
The status is updated as soon as the chat is deleted

**Describe alternatives you've considered**
The sound notification seems to work properly so perhaps there is a way to leverage that logic to update the status. Alternatively it may be fixed by programmatically refreshing the page when the chat is deleted.

**Additional context**
Tested with Edge 97.0.1072.69 (Official build) (64-bit), Firefox 96.0.2 (64-bit)

**Comment by muke1908** [comment]
@softvisioneer thanks for reporting the bug. I'll look into this.

**Comment by jonatan5524** [comment]
I can work on it

**Comment by muke1908** [comment]
`getUsersInChannel returns 404` -which is expected.  
> Alice is disconnected do we really need to call getUsersInChannel 
We should rather refactor `getSetUsers` function so that that if `getUsersInChannel` return 404, it should set empty array in channel.
