### ISSUE TITLE
Bug: node-fetch require error

### ISSUE THREAD

**Issue by jonatan5524** [muke1908/chat-e2ee#210]
**Bug:**
I have cloned the repo for the first time, ran npm install, and npm run dev.
The following error is presented:
```bash
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/jonatan/git/chat-e2ee/node_modules/node-fetch/src/index.js from /home/jonatan/git/chat-e2ee/backend/external/imgbb.js not supported.
Instead change the require of index.js in /home/jonatan/git/chat-e2ee/backend/external/imgbb.js to a dynamic import() which is available in all CommonJS modules.
```

**Steps to Reproduce:**
1. clone the repository
2. run npm install
3. run npm run dev

**Context:**
System: Ubuntu 20.04.3 LTS
Node version: v16.14.1

**Comment by jonatan5524** [comment]
I have searched for the error, and the problem is in node-fetch version, in node-fetch v3 required is not supported:
https://github.com/node-fetch/node-fetch#commonjs
I would like to contribute and fix this error by changing the node-fetch version to v2

**Comment by muke1908** [comment]
@jonatan5524 sure, go ahead!

**Comment by jonatan5524** [comment]
I am new to contributing to open source, so sorry for the ignorance.
How to set up my own MongoDB instance for development with the relevant collections?

**Comment by muke1908** [comment]
Try following this document: https://github.com/muke1908/chat-e2ee/wiki/ENV-variables 

You can message [here](https://gitter.im/chat-e2ee/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge), if you need any help.
https://gitter.im/chat-e2ee/community

**Comment by jonatan5524** [comment]
Thank you, maybe worth adding this wiki page to the contributing guidelines, I will be happy to do it after this issue.
