### ISSUE TITLE
Support typescript

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#215]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Current code is written in javascript, however, adding support for typescript will help in gradual migration. 

**Describe alternatives you've considered**

**Comment by alirezariahi** [comment]
Hi, I can help to migrate to typescript. can you let me start this job?

**Comment by alirezariahi** [comment]
finished

**Comment by ArslanYM** [comment]
Is this issue resolved?

**Comment by muke1908** [comment]
Resolved
