### ISSUE TITLE
Create component for chat link display

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#26]
Create a react component that will take `content` as a prop.

Functionalities: 
1. It'll have a copy button
2. Clicking on the copy button, the content will be copied to the clipboard.
3. If someone clicks on the text it should get selected.

Example:

![2020-07-22 18 27 06](https://user-images.githubusercontent.com/20297989/88195762-0f530780-cc49-11ea-94ca-9957816da496.gif)

**Comment by gagan-aryan** [comment]
I am working on this issue and I am trying to use useRef hook to access copy the text inside the textarea but I am encountering the attached error. 
![Screenshot from 2020-07-23 03-13-07](https://user-images.githubusercontent.com/62807661/88232056-d475c180-cc92-11ea-9fa6-0a38a6256ea8.png)

**Comment by gagan-aryan** [comment]
Never mind, resolved.
