### ISSUE TITLE
Add unit test for channelValid function

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#268]
https://github.com/muke1908/chat-e2ee/blob/master/backend/api/chatLink/utils/validateChannel.ts

**Comment by estefysc** [comment]
Hello @muke1908, I have been looking for "good first issues", so I can start contributing to open source. This seems a good one for me and would like to work on it. If it seems ok with you, would you be able to assign me to it?

**Comment by muke1908** [comment]
@estefysc sure, go ahead!

**Comment by estefysc** [comment]
Thanks!

**Comment by estefysc** [comment]
Awesome! Thank you.
