### ISSUE TITLE
Update the readme.md with the instructions for captcha configuration

### ISSUE THREAD

**Issue by gagan-aryan** [muke1908/chat-e2ee#28]
The home route contains a captcha that needs to configured while setting up the development environment. Update the readme summarizing the below steps.

- Obtain key from the google captcha site.
- Create the .env files in the root and client directory. 
- Use the relevant keys in both the .env files.

**Comment by muke1908** [comment]
https://github.com/muke1908/chat-e2ee/wiki/Captcha
