### ISSUE TITLE
Add typescrript support to React Client

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#282]
Client-side code is written in JS, and although react-script support TS by default, some changes are required.
 - Change the file extension
 - Add required types just to make the build successful.

**Comment by suman313** [comment]
Hi, @muke1908, 
I have gone through the project. I can add typescript support to the client side code which is now written in vanilla js.
I want to work on this issue.

**Comment by muke1908** [comment]
@suman313 Sure, go ahead.
