### ISSUE TITLE
Write UT for cryptoUtils module

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#287]
Write unit test for cryptoUtils module, mock all necessary external browser dependency. 
https://github.com/muke1908/chat-e2ee/blob/master/service/src/crypto.ts

**Comment by estefysc** [comment]
Hey, @muke1908. Would like to work on these tests as well! Might take me a bit longer though. Let me know if thats ok with you.

**Comment by estefysc** [comment]
@muke1908 perfect! I will. Thanks.

**Comment by estefysc** [comment]
Hey @muke1908 just wanted to double check.. are the tests just for "cryptoUtils", meaning the functions generateKeypairs, encryptMessage, and decryptMessage? Or should I include tests for all the other functions in the file?

**Comment by muke1908** [comment]
@estefysc Yes those three are enough as only they are exported.

**Comment by estefysc** [comment]
@muke1908 I am having issues mocking the window.crypto.subtle dependency. I have done some research, and I have found info that talks about using the node crypto.webcrypto property like so:

```
const crypto = require('crypto').webcrypto;
global.crypto = crypto;
```

Would this be ok?

**Comment by muke1908** [comment]
@estefysc You should not use the external module for testing. It needs to be mocked. 
You can just assign some mock module to global.crypto like 
global.crypto = { 
subtle: {
        generateKey: jest.fn(),
        encrypt: jest.fn(),
        decrypt: jest.fn(),
        importKey: jest.fn(),
        exportKey: jest.fn()
    }
}

also, you need to add mockReturnvalue to each func like: 
generateKey: jest.fn().mockReturnValue({ publicKey:'test-public-key', privateKey: 'test-private-key' })

it should work

**Comment by estefysc** [comment]
@muke1908 I tried your suggestion and a couple versions of it, but I am seeing the following error in all cases:

```
The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: window is not defined
```

**Comment by muke1908** [comment]
can You push your code and create a PR, I’ll check

**Comment by estefysc** [comment]
Ok, just did.
