### ISSUE TITLE
Allow to set server endpoint in chate2ee/service module

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#288]
Currently the module makes all request to `/` path. Allow user to set any base url. 
Take URL as an arg in `createChatInstance` function.

https://github.com/muke1908/chat-e2ee/blob/94f764f4937632e34e4a18ce6ab13e783c032e52/service/src/sdk.ts#L14

**Comment by KalebArmbrust** [comment]
@muke1908 Hey, I would love to give this a go, can you assign this to me?

**Comment by muke1908** [comment]
@KalebArmbrust sure , go ahead

**Comment by KalebArmbrust** [comment]
@muke1908 Hey this is all pretty new to me. Can you possibly give me a hint or some direction? All I've done so far is add URL as an argument like you mentioned.
![Screenshot 2023-05-11 114637](https://github.com/muke1908/chat-e2ee/assets/68127436/264e0622-a61d-454c-a50f-94f414c03a13)

**Comment by muke1908** [comment]
Hi @KalebArmbrust , 
The simplest way I can suggest is instead of taking it in arg, let's define a separate function `setConfig`
```
const chate2eeConfig = {};
export const setConfig = (apiURL, socketURL) => {
     chate2eeConfig = { apiURL, socketURL }
}

export const configContext = () => chate2eeConfig;
```

import configContext in (makeRequest)[https://github.com/muke1908/chat-e2ee/blob/master/service/src/makeRequest.ts] file, and use it in `BASE_URI`, `const { apiURL }  = configContext();`

export the `setConfig` from sdk.ts so that users can explicitly call `setConfig` to set URLs before creating an instance.

**Comment by KalebArmbrust** [comment]
@muke1908 I have added the new function in sdk.ts and exported it, and imported configContext to the makeRequest.ts file but I am not sure how to use it in the BASE_URI

![Screenshot 2023-05-12 100854](https://github.com/muke1908/chat-e2ee/assets/68127436/31199381-2608-40d7-a08c-5c7ddfcb337e)

![Screenshot 2023-05-12 100906](https://github.com/muke1908/chat-e2ee/assets/68127436/41317127-fbc3-47b6-a162-dc27244cf9f0)

**Comment by KalebArmbrust** [comment]
@muke1908 Like this?

![Screenshot 2023-05-12 102401](https://github.com/muke1908/chat-e2ee/assets/68127436/f4017449-396f-4eb3-b5f1-cc5e1f059cf9)

**Comment by muke1908** [comment]
yes but no curly braces. simply 
const BASE_URI = apiURL || (process.env.NODE_ENV === "production" ?  'https://chat-e2ee-2.azurewebsites.net' : '')

**Comment by muke1908** [comment]
This is fine!

**Comment by KalebArmbrust** [comment]
@muke1908 Great, is there anything else or should I make a pull request?

**Comment by muke1908** [comment]
yes, please create a PR. I’ll write comments there if any )
