### ISSUE TITLE
Remove the PIN UI component

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#305]
Remove the `PinDisplay`  component as it's not being used anywhere.
<img width="870" alt="Screenshot 2023-06-30 at 21 48 03" src="https://github.com/muke1908/chat-e2ee/assets/20297989/bfb18c3a-4ef0-4b59-9634-913405fd2c24">

**Comment by suitcasemedia** [comment]
Hello I'd like to work on this

**Comment by muke1908** [comment]
> Hello I'd like to work on this

Sure!
