### ISSUE TITLE
Messaging: Create a layout for messaging page

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#31]
When someone visits the generated link (#2), this page will open up. 
Dir: `client/src/pages/messaging/index`

Check the attached image for reference.

--- 

This is just for the information **not in the scope of this issue** :
In this page following things will be handled: 
 - Public key exchange
 - Storing public key in localStorage
 - Chatting interface

---

![chat](https://user-images.githubusercontent.com/20297989/88453962-88827280-ce74-11ea-834d-15e24511e6ae.png)

**Comment by gagan-aryan** [comment]
Getting the below error upon following the generated link.
