### ISSUE TITLE
Setup webrtc

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#310]
Set up a basic webrtc support to front-end to support audio/video call.

**Comment by HarshSingh21** [comment]
I want to contribute in webrtc , can we build  this together  .

**Comment by muke1908** [comment]
Hi @HarshSingh21 sure. Let's do it in smaller PRs otherwise, it can be pretty big. Within the scope of this PR, let's just add a very basic webrtc setup in chate2ee/service - https://github.com/muke1908/chat-e2ee/tree/master/service

**Comment by HarshSingh21** [comment]
Hi , @muke1908 sure . I will be working on it .
