### ISSUE TITLE
in /chat page send button is not working

### ISSUE THREAD

**Issue by suman313** [muke1908/chat-e2ee#316]
I am running the latest version
 I checked the documentation and found no answer
 I checked to make sure that this issue has not already been filed

**Expected Behavior**

The send button in /chat page should send the message on click

**Current Behavior**

The send button in /chat page is not working on click.

- Operating System: windows 10
- Node version: ACTIVE LTS 18

**Comment by muke1908** [comment]
https://github.com/muke1908/chat-e2ee/pull/317
