### ISSUE TITLE
Display the action is "in-progress"

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#321]
When a user clicks on the button, it should show some kind of loader or change the button text to "Creating..."

<img width="871" alt="Screenshot 2023-07-12 at 13 19 21" src="https://github.com/muke1908/chat-e2ee/assets/20297989/693c7f71-ca18-44ac-862e-b867cddc8a5e">

**Comment by codebysid** [comment]
hey, i would like to work on this, should i start ?
