### ISSUE TITLE
Allow user to set nickname

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#326]
Right now the nickname is hard-coded as Alice.Pass an optional param, username,  in setChannel method
(channelId: string, userId: string, userName?: string);

https://github.com/muke1908/chat-e2ee/blob/114a99d50baa587cad7c603a24610df2c3cc5ca4/service/src/sdk.ts#L79

Scope of this ticket:
1 - add 3rd optional param in setChannel
2 - store it in a private variable in ChatE2EE class.

**Comment by karandeep4423** [comment]
could you assign me this issue?

**Comment by karandeep4423** [comment]
hi, you want that i write these two lines only or should write compelete code for frontend and backend as well, like there would be input place in frontend where user can type his name. Kindly expain me in a detail, as it is my first contribution in open source project so kindly corporate

**Comment by muke1908** [comment]
@Yashita1512 Not sure if @karandeep4423 is working. Can you confirm if you are working on it (@karandeep4423 )?

**Comment by Yashita1512** [comment]
I will wait until tomorrow for his reply, else I will try solving it. Thankyou for  the response @muke1908.

**Comment by karandeep4423** [comment]
@muke1908 @Yashita1512  i am working on it

**Comment by muke1908** [comment]
It's fine. You can push it.

**Comment by karandeep4423** [comment]
but i did not include in stringfy 
  public async setChannel(channelId: string, userId: string, userName: string): Promise<void> {
        this.checkInitialized();
        logger.log(`setChannel(), ${JSON.stringify({ channelId, userId })}`);
        this.channelId = channelId;
        this.userId = userId;
        await sharePublicKey({ publicKey: this.publicKey, sender: this.userId, channelId: this.channelId });
        this.socket.joinChat({ publicKey: this.publicKey, userID: this.userId, channelID: this.channelId })
        await this.getPublicKey(logger);
        return;
    }

**Comment by muke1908** [comment]
Please create a PR. It'll be easy to review there
