### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by BhushanNalawade** [muke1908/chat-e2ee#328]
Bug Report : 

Expected Behavior :
when click on Enter either it will have to sends the message or have to make new line .

Current Behavior :
What is the current behavior?
when click on enter it clears all the messages and when click shift + enter then it will go in new window with blank format.

Failure Information :
1.have to check for button events to specifying it's uses like enter and shift + enter.
2.Emoji options not available on mobile devices.

Steps to Reproduce :
1. Connect with the ally
2. after connecting write some messages and hit enter.
3. you will get to see that messages are removed from the format.

**Context**

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

- Operating System: Windows 10
- Node version - v18.16.0

**Comment by felipolis** [comment]
Hello how are you? I was also bothered by this bug in the application. I would like to try to solve it! Could you assign me to this issue?

**Comment by muke1908** [comment]
Hi @felipolis, sure go ahead!

**Comment by felipolis** [comment]
I'm working on it! Thanks :D

**Comment by felipolis** [comment]
Hi @muke1908 , I just submitted a pull request fixing this problem. Could you take a look?

**Comment by muke1908** [comment]
Thank @felipolis! merged
