### ISSUE TITLE
Display chat session statuses in UI

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#33]
Once clicked the chat link, following things happen.
1. It checks for the participant's public key. [getSetUsers](https://github.com/muke1908/chat-e2ee/blob/65ccf6fdb2852d885370787f0d01e343199fbee4/client/src/pages/messaging/index.js#L125)
2. It generates its key pair and shares the public key.  [exchangePublicKey](https://github.com/muke1908/chat-e2ee/blob/65ccf6fdb2852d885370787f0d01e343199fbee4/client/src/pages/messaging/index.js#L65)
3. In case public key not found in step 1, it waits for the other user to join and request public key once other user joins the chat.

Users can start chatting only once above steps are finished. Display the above statuses in the UI so that users are aware of stuff that are happening behind the scene.

**Statuses need to displayed on UI:**
1.  Checking for user.
2.  Sharing public key.
3.  Waiting for user.
4.  Online.

**Comment by AudreyKj** [comment]
can i work on this?

**Comment by muke1908** [comment]
> can i work on this? :)

Hi! Can you take a look on this first https://github.com/muke1908/chat-e2ee/issues/79?

**Comment by AudreyKj** [comment]
sure!

**Comment by muke1908** [comment]
Closing as it became irrelevant
