### ISSUE TITLE
Messaging: component to display list of messages

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#37]
Create a component that accepts an array of objects as a prop where the objects represent one message block, and it should render the messages in a list view (Ref: attached image).
Example prop: 
```
cosnt data = [
    {
       self: true,
       body: "Hey Alice"
    }, {
       self: false,
       body: "Hi Bob"
    }
]

<MessageList data={data} />
```
![chat (1)](https://user-images.githubusercontent.com/20297989/88474358-461d6c00-cf2e-11ea-95e0-53ff6fc9d576.png)

Note: The message block should align accordingly. If it's sent by you (i.e. `self: true`) it should appear on the right side of you.

**Comment by muke1908** [comment]
Blocked on: https://github.com/muke1908/chat-e2ee/issues/31

**Comment by gagan-aryan** [comment]
What is the tool that is being used to create these ui designs?

**Comment by muke1908** [comment]
> What is the tool that is being used to create these ui designs?

Figma https://www.figma.com/
