### ISSUE TITLE
Show error if webrtc call is not supported

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#379]
Frontend should show error if `startCall` is called but it's not supported.

Error thrown here:
https://github.com/muke1908/chat-e2ee/blob/905c8c0f1048d9a78509a7bcfed75bda361d8c54/service/src/sdk.ts#L232

Error should be caught here and shown it to user. 
https://github.com/muke1908/chat-e2ee/blob/905c8c0f1048d9a78509a7bcfed75bda361d8c54/client/src/components/Messaging/UserStatusInfo.tsx#L46

**Comment by ameysanyal** [comment]
I want to work on this issuse, Please assign it to me
