### ISSUE TITLE
Prevent the user from sending empty messages

### ISSUE THREAD

**Issue by gagan-aryan** [muke1908/chat-e2ee#45]
Currently, a user can send empty messages to the person he/she is chatting with. This might include an empty string(which is a message) or a message containing _only_  'n' number of spaces. 

~Disable the send button as long as the person(the one sending the message) enters a non-empty message.~

Prevent submit for the empty message - let's just do `alert('Please enter your message')` 
https://github.com/muke1908/chat-e2ee/blob/ab778f4d33fda2d15245ac1bc9625b4103b789b3/client/src/pages/messaging/index.js#L71

**Comment by muke1908** [comment]
This needs to be handled both in frontend and backend. 

Needs to validate here in the backed 
https://github.com/muke1908/chat-e2ee/blob/dc79482a22df8a5cb53ff9b2eeaff95353110974/backend/api/messaging/index.js#L8

**Comment by jradha11** [comment]
@muke1908 can I start working on this issue?

**Comment by muke1908** [comment]
> @muke1908 can I start working on this issue?

Sure!
