### ISSUE TITLE
desktop: Add basic emoji support 

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#54]
For non-mobile devices, add support for emoji.

- Create a util function that detects whether it's a mobile device or not. 
- If not a mobile device, add a row of basic emojis right above the text area. (Chat page)

**Comment by zygisS22** [comment]
Can i try this one?

**Comment by muke1908** [comment]
@zygisS22 Sure!

**Comment by gagan-aryan** [comment]
@zygisS22 are you still working on this? Mind if I give it a shot?

**Comment by zygisS22** [comment]
> 
> 
> @zygisS22 are you still working on this? Mind if I give it a shot?

yeah sure, i been busy with work unfortunately haven't done much yet 😞
