### ISSUE TITLE
Add image picker

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#59]
Allow users to attach image in chat.
Create _util_ function and applicable UI(Check the screenshot) that allow user to pick an image and return `base64`
Asset attached.

Util reference: https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL

![Untitled](https://user-images.githubusercontent.com/20297989/89718658-17d96b00-d9c9-11ea-93d6-139ecf01fca2.png)

Asset:  
![asset](https://user-images.githubusercontent.com/20297989/89718670-2b84d180-d9c9-11ea-9c4c-06115c401175.png)

**Comment by aUsefulMethod** [comment]
I'd like to attempt working on this, if that is ok?

**Comment by muke1908** [comment]
@aUsefulMethod Sure!

**Comment by AudreyKj** [comment]
@aUsefulMethod  are you still working on it?  otherwise, I'm also happy to do it!

**Comment by aUsefulMethod** [comment]
Sure, go ahead :)
