### ISSUE TITLE
Button to retry fetching public key

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#60]
Show a button:
-When a user joins the session, we try to get its public key  [on join](https://github.com/muke1908/chat-e2ee/blob/e08a23673a24cd41967c9d2d4dadb4ed1b39f0bf/client/src/pages/messaging/index.js#L185)  

-In case, there is no key available at that moment or the request fails, show a button at the top that will allow the user to fetch the key again. Ref attached image.

-When someone clicks the button, call `getSetUsers(channelID);`. 

While loading:
 - spin the button for better UX.
 - should not be clickable. 

https://github.com/muke1908/chat-e2ee/blob/e08a23673a24cd41967c9d2d4dadb4ed1b39f0bf/client/src/pages/messaging/index.js#L132

-Once the key is received, make sure the button is not visible anymore.

Ref design:
![Untitled](https://user-images.githubusercontent.com/20297989/91587501-87ef6700-e95f-11ea-9a24-02945f98693e.png)

**Comment by muke1908** [comment]
Asset:
![refresh](https://user-images.githubusercontent.com/20297989/91587788-eae0fe00-e95f-11ea-8d21-fd75871ec16c.png)

**Comment by AudreyKj** [comment]
@muke1908 can i work on this? :)

**Comment by muke1908** [comment]
@AudreyKj Sure!

**Comment by AudreyKj** [comment]
@muke1908 i'm working on this, but is there a ref on how the button should look like before loading?

**Comment by muke1908** [comment]
@AudreyKj , yes, I have added a design above.

**Comment by AudreyKj** [comment]
@muke1908 so the button will look like the design ref before and during loading, got it! sorry i got confused!

**Comment by muke1908** [comment]
While loading:

spin the button for better UX.
should not be clickable.

**Comment by muke1908** [comment]
@AudreyKj  this one https://github.com/muke1908/chat-e2ee/issues/130 might be interesting for you as well!

**Comment by AudreyKj** [comment]
@muke1908  I just worked on this: https://github.com/muke1908/chat-e2ee/pull/133
(will tackle #130 once this merged!) thank you :)

**Comment by muke1908** [comment]
@AudreyKj Can you please resolve the conflicts https://github.com/muke1908/chat-e2ee/pull/133

**Comment by AudreyKj** [comment]
@muke1908 done
