### ISSUE TITLE
Button remains enabled even after the verification gets expired

### ISSUE THREAD

**Issue by gagan-aryan** [muke1908/chat-e2ee#62]
Even after the expiry of captcha the Generate Link Button stays enabled but it should get back to disabled state since the user has to verify again. 

![issue2](https://user-images.githubusercontent.com/62807661/89888397-80a12d00-dbed-11ea-900c-e7da5a5a547f.png)

**Comment by DarkSouL11** [comment]
@gagan-aryan  @muke1908 I am picking this up

**Comment by muke1908** [comment]
@all-contributors please add @DarkSouL11  for infrastructure and code
