### ISSUE TITLE
Save theme settings in localStorage

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#65]
The theme can be toggled between light and dark - however, it doesn't store the state hence becomes dark on refresh. Save the selected theme in localStorage for better UX.

Use the util function at client/src/utils/storage.js
Toggle component: https://github.com/muke1908/chat-e2ee/blob/master/client/src/components/ThemeToggle/index.js

**Comment by gagan-aryan** [comment]
Haven't played around with localStorage. Can I take up this issue?

**Comment by muke1908** [comment]
@gagan-aryan sure!
