### ISSUE TITLE
Code smell: Rename "loadScript.js" file to "loadJS.js"

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#66]
https://sonarcloud.io/project/issues?id=muke1908_chat-e2ee&issues=AXOMogkpaTtxhThidclw&open=AXOMogkpaTtxhThidclw

**Comment by AudreyKj** [comment]
is this still open? @muke1908 i'm happy to work on it

**Comment by muke1908** [comment]
@AudreyKj Sure!
