### ISSUE TITLE
Code smell: Rename "request.js" file to "makeRequest.js"

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#67]
https://sonarcloud.io/project/issues?id=muke1908_chat-e2ee&issues=AXOMogkdaTtxhThidclv&open=AXOMogkdaTtxhThidclv

**Comment by AudreyKj** [comment]
@muke1908 is this still open? i'm happy to work on it if it is

**Comment by muke1908** [comment]
@AudreyKj Sure!

**Comment by AudreyKj** [comment]
@muke1908 done :) 

PR: https://github.com/muke1908/chat-e2ee/pull/70
