### ISSUE TITLE
Create a style guide

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#7]
Create a style guide that will be followed across the project.
It can be a basic CSS file or styled component theme.
https://styled-components.com/docs/advanced

Required properties:

- Primary color
- Secondary color
- Large font size
- Medium font size
- Small font size

**Comment by AudreyKj** [comment]
@muke1908 is this still open? I love CSS and would love to work on this!

**Comment by muke1908** [comment]
@AudreyKj 
I would love to understand how are you going to approach this as well :)

**Comment by AudreyKj** [comment]
@muke1908 yeah i was thinking about it and it would be great to have more info: 
- does the project have design prototypes? 
- where would this style guide live in the project? in the root folder? in /public?

**Comment by AudreyKj** [comment]
@muke1908 is this still open?

**Comment by muke1908** [comment]
@AudreyKj Hi,this issue looks like not relevant anymore.
