### ISSUE TITLE
Improve auto scroll experience for chat messages

### ISSUE THREAD

**Issue by DarkSouL11** [muke1908/chat-e2ee#77]
Auto scroll to new message should happen in the following scenarios
- [x] Whenever user sends a message
- [x] Whenever user receives a message and he is currently at the bottom of the message list

Auto scroll to new message should not happen in the following scenarios
- [ ] User is reading old messages(i.e, is not scrolled to the bottom of chat window). In this case we can show an indicator which says `X New messages` which when clicked can scroll to the first unread message.

**Comment by loneWarrior581** [comment]
hello everyone i am intrested in contributing to this project so can anyone help me in setting up this project in my local machine as it is my first open source project.

**Comment by muke1908** [comment]
Hi @loneWarrior581,
> hello everyone i am intrested in contributing to this project so can anyone help me in setting up this project in my local machine as it is my first open source project.

Here are the instructions to setup the project:
https://github.com/muke1908/chat-e2ee#for-developers

**Comment by loneWarrior581** [comment]
@muke1908  Sir I have set up the project on my computer and facing issues on how to bypass the front page to reach the chat section as the private link is not able to generate. Iwould be very keen if I would be solving some issues to make my **first contribution**.
![chat e2ee](https://user-images.githubusercontent.com/67538935/91635830-5044f580-ea19-11ea-958e-9b60e3af887f.PNG)

**Comment by muke1908** [comment]
@loneWarrior581 Looks like you have not configured the google captcha. Please go through this https://github.com/muke1908/chat-e2ee/wiki/Captcha

Instead of this issue, you start picking an issue from [good-first-issue](https://github.com/muke1908/chat-e2ee/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)

**Comment by loneWarrior581** [comment]
### Help needed
@muke1908  sir I am getting an error while setting up it says : **MONGO DB ERROR!** although i have given the mongo db uri. And also what are the values to be given in the field **CHAT_LINK_DOMAIN=' '** and **MONGO_DB_NAME=' '**. Also I am not able to find the location of **IMAGE_BB_API_KEY** to be given .

**Comment by muke1908** [comment]
> ### Help needed
> @muke1908 sir I am getting an error while setting up it says : **MONGO DB ERROR!** although i have given the mongo db uri. And also what are the values to be given in the field **CHAT_LINK_DOMAIN=' '** and **MONGO_DB_NAME=' '**. Also I am not able to find the location of **IMAGE_BB_API_KEY** to be given .

Hi @loneWarrior581 
Get `IMAGE_BB_API_KEY` from https://api.imgbb.com/.

For mongodb, you have to create a database, that you have to assign to `MONGO_DB_NAME`.

What error are you getting anyway?

**Comment by loneWarrior581** [comment]
@muke1908  Sir I am not able to find the directory where the variable **IMAGE_BB_API_KEY** is located. And also how to make it possible to make instances so that they can communicate within the localhost for the _testing_ purpose in our local machine

**Comment by muke1908** [comment]
> @muke1908 Sir I am not able to find the directory where the variable **IMAGE_BB_API_KEY** is located. And also how to make it possible to make instances so that they can communicate within the localhost for the _testing_ purpose in our local machine

@loneWarrior581 `IMAGE_BB_API_KEY` is in './env` check [sample](https://github.com/muke1908/chat-e2ee/blob/master/.env.sample)

Run `npm install`, then run `npm run dev`.

**Comment by AudreyKj** [comment]
@DarkSouL11 hey! Can I work on this?

**Comment by DarkSouL11** [comment]
@AudreyKj Yeah sure. @muke1908 I believe this is not picked by anyone yet

**Comment by AudreyKj** [comment]
ok!

**Comment by GJ-16** [comment]
Hey, can anybody tell me how to approach this? if no one is working I'll give a try.

**Comment by amreekminocha** [comment]
Hii.. Can I get assigned to this role?
I would love to contribute

**Comment by muke1908** [comment]
Sure, go ahead.

**Comment by parthamk** [comment]
- [ ] User is reading old messages(i.e, is not scrolled to the bottom of chat window). In this case we can show an indicator which says X New messages which when clicked can scroll to the first unread message.

I think I can fix it

**Comment by iamabhshk** [comment]
Is anyone working on this? If not can I give a try?

**Comment by muke1908** [comment]
@JasmikDobariya Sure, please go ahead!

**Comment by JasmikDobariya** [comment]
i can fix scroll issue chack i am send pull request

**Comment by hfdem** [comment]
> @muke1908 i fixed scroll issue! check my pull request if any problem in my code send me mail

Hi, I met an issue, the "New Messages" pops up both when sending messages continuously and receiving messages. It’s quite annoying. Could you please check and optimize it?

**Comment by hfdem** [comment]
Now cliking the ‘New messages’ will jumps to the bottom. Can someone improve it so it jumps to the first unread message?
