### ISSUE TITLE
Set captcha theme based on the site theme

### ISSUE THREAD

**Issue by gagan-aryan** [muke1908/chat-e2ee#79]
Currently, the captcha is always seen in its dark version and doesn't change its theme upon pressing the toggle button. Correct this behavior and make it consistent with the theme. 

Get mode and pass appropriately.  
`const [darkMode] = useContext(ThemeContext);`
https://github.com/muke1908/chat-e2ee/blob/afe9735828ad8819d4518119f9150e282113d296/client/src/pages/chatlink/captcha.js#L10

**Comment by AudreyKj** [comment]
just fixed this: https://github.com/muke1908/chat-e2ee/pull/83

**Comment by muke1908** [comment]
@AudreyKj thanks! merged

**Comment by muke1908** [comment]
@AudreyKj re-opening the issue as it's not working as expected. 
Looks like it doesn't re-render if it's already loaded. Need to investigate.

**Comment by AudreyKj** [comment]
will look into it as well - it might be that captcha buttons need page refresh to re-render.

**Comment by AudreyKj** [comment]
just worked on it and found a solution: https://github.com/muke1908/chat-e2ee/pull/84
