### ISSUE TITLE
Remove duplicate property from css

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#85]
https://sonarcloud.io/project/issues?id=muke1908_chat-e2ee&issues=AXOjmn81ijryR0MKnQeU&open=AXOjmn81ijryR0MKnQeU

**Comment by imlaxman** [comment]
I will work on this

**Comment by imlaxman** [comment]
https://github.com/muke1908/chat-e2ee/pull/86

**Comment by imlaxman** [comment]
submitted fore review

**Comment by muke1908** [comment]
Closed by https://github.com/muke1908/chat-e2ee/pull/86

**Comment by muke1908** [comment]
@all-contributors please add @imlaxman  for code
