### ISSUE TITLE
White background is visible in dark theme.

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#93]
In dark theme, the bottom part should also be dark not white.

<img width="720" alt="Screen Shot 2020-08-22 at 9 10 46 PM" src="https://user-images.githubusercontent.com/20297989/90962876-12e1e480-e4bc-11ea-88ec-48af5c1a4ba1.png">

**Comment by AudreyKj** [comment]
@muke1908 can i work on this? :)

**Comment by muke1908** [comment]
Hi @AudreyKj, looks like this issue is fixed. 
If you are looking to do something visual you might look into this #60
