### ISSUE TITLE
Messaging: Preview picked image

### ISSUE THREAD

**Issue by muke1908** [muke1908/chat-e2ee#94]
In messaging page, display the image when picked for sending.

Ref: https://github.com/muke1908/chat-e2ee/blob/6e27e36a1efe3321c16f754b2cb097a9276f2e88/client/src/components/Messaging/NewMessageForm.js#L30

Lets abstract _image selection and preview_ as a separate component.  Use the `Image` component (`components/Image/`) to display the image.

Design suggestion:
<img width="808" alt="Screen Shot 2020-08-22 at 9 48 29 PM" src="https://user-images.githubusercontent.com/20297989/90963565-4c691e80-e4c1-11ea-92c3-2344af1cd591.png">

**Comment by AudreyKj** [comment]
hey! can i work on this?

**Comment by muke1908** [comment]
Hi @AudreyKj , @tskull01 already working on it. You can take a look at his PR https://github.com/muke1908/chat-e2ee/pull/108
