### ISSUE TITLE
Instructions to setup environment for development

### ISSUE THREAD

**Issue by sakshianand** [muke1908/chat-e2ee#96]
MONGO_URI=mongodb+srv://<username>:<password>@cluster0-zbsik.mongodb.net
MONGO_DB_NAME=''"
CHAT_LINK_DOMAIN=''"

Where to generate these from? This is required to setup the dev environment.
@muke1908 Can you help me out?

**Comment by muke1908** [comment]
https://github.com/muke1908/chat-e2ee/wiki/ENV-variables
